import { db, categoriesTable, productsTable } from "@workspace/db";
import { sql } from "drizzle-orm";
import { logger } from "./logger";

const categories = [
  { id: 1, name: "Rings", slug: "rings", imageUrl: "/images/ring1.jpg" },
  { id: 2, name: "Earrings", slug: "earrings", imageUrl: "/images/earring1.jpg" },
  { id: 3, name: "Mangalsutra", slug: "mangalsutra", imageUrl: "/images/cat-mangalsutra.png" },
  { id: 4, name: "Necklace", slug: "necklace", imageUrl: "/images/necklace1.jpg" },
  { id: 5, name: "Bracelet", slug: "bracelet", imageUrl: "/images/bangle1.jpg" },
  { id: 6, name: "Chain", slug: "chain", imageUrl: "/images/chain1.jpg" },
  { id: 7, name: "Pendant", slug: "pendant", imageUrl: "/images/necklace4.jpg" },
];

const products = [
  {
    id: 1,
    name: "22K Gold Heart & Starburst Diamond Ring",
    description: "A radiant 22K gold ring featuring an intricate heart and starburst motif set with brilliant diamonds. Hallmarked K.21, this statement piece blends traditional craftsmanship with timeless elegance.",
    price: "$480",
    originalPrice: "$560",
    imageUrl: "/images/ring1.jpg",
    categoryId: 1,
    categoryName: "Rings",
    isNewArrival: true,
    isTrending: true,
    badge: "New",
    weight: "4.45g",
  },
  {
    id: 2,
    name: "22K Gold Leaf & Flower Ring with Pearl Accent",
    description: "Delicately crafted in 22K gold, this floral ring showcases a botanical leaf-and-flower design adorned with a lustrous pearl accent. Hallmarked K.21, each detail is hand-finished by master artisans.",
    price: "$390",
    originalPrice: "$460",
    imageUrl: "/images/ring2.jpg",
    categoryId: 1,
    categoryName: "Rings",
    isNewArrival: true,
    isTrending: false,
    badge: "New",
    weight: "3.62g",
  },
  {
    id: 3,
    name: "22K Gold Three-Stone Ring with Black & Diamond Accents",
    description: "An opulent 22K gold ring set with three prominent stones flanked by black onyx and sparkling diamonds. Hallmarked K.21, this ring carries an unmistakable air of luxury and heritage.",
    price: "$980",
    originalPrice: "$1150",
    imageUrl: "/images/ring3.jpg",
    categoryId: 1,
    categoryName: "Rings",
    isNewArrival: false,
    isTrending: true,
    badge: "Trending",
    weight: "14.95g",
  },
  {
    id: 4,
    name: "22K Gold Double Woven Basket Ring with Diamonds",
    description: "This striking 22K gold ring features a double woven basket weave design encrusted with brilliant-cut diamonds. Hallmarked K.21, it is a masterpiece of precision and artisanal skill.",
    price: "$648",
    originalPrice: "$760",
    imageUrl: "/images/ring4.jpg",
    categoryId: 1,
    categoryName: "Rings",
    isNewArrival: true,
    isTrending: true,
    badge: "New",
    weight: "6.00g",
  },
  {
    id: 5,
    name: "22K Gold Cuban-Link Statement Ring",
    description: "A bold and timeless 22K gold Cuban-link ring with a chunky, polished finish. Hallmarked K.21, this piece makes a powerful statement that transitions effortlessly from day to evening wear.",
    price: "$880",
    originalPrice: "$1020",
    imageUrl: "/images/ring5.jpg",
    categoryId: 1,
    categoryName: "Rings",
    isNewArrival: false,
    isTrending: true,
    badge: "Trending",
    weight: "14.35g",
  },
  {
    id: 6,
    name: "Set of 4 Plain Ribbed Gold Bangles",
    description: "A classic set of four finely ribbed 22K gold bangles with a smooth polished finish. Hallmarked K.21, these stackable bangles are an everyday luxury that elevates any outfit.",
    price: "$1,480",
    originalPrice: "$1,720",
    imageUrl: "/images/bangle1.jpg",
    categoryId: 5,
    categoryName: "Bracelet",
    isNewArrival: true,
    isTrending: false,
    badge: "New",
    weight: "14.72g",
  },
  {
    id: 7,
    name: "Set of 4 Patterned Cutout Gold Bangles",
    description: "Four elegant 22K gold bangles each featuring a delicate cutout lattice pattern. Hallmarked K.21, this set pairs tradition with artful modern design.",
    price: "$1,290",
    originalPrice: "$1,500",
    imageUrl: "/images/bangle2.jpg",
    categoryId: 5,
    categoryName: "Bracelet",
    isNewArrival: true,
    isTrending: true,
    badge: "New",
    weight: "11.97g",
  },
  {
    id: 8,
    name: "Set of 4 Twisted Rope Gold Bangles",
    description: "A stunning set of four 22K gold bangles in a richly detailed twisted rope pattern. Hallmarked K.21, the interlocking texture catches light beautifully, creating an ever-changing shimmer.",
    price: "$1,560",
    originalPrice: "$1,820",
    imageUrl: "/images/bangle3.jpg",
    categoryId: 5,
    categoryName: "Bracelet",
    isNewArrival: false,
    isTrending: true,
    badge: "Trending",
    weight: "15.37g",
  },
  {
    id: 9,
    name: "Set of 4 Diamond-Cut Ribbed Gold Bangles",
    description: "Four bold 22K gold bangles featuring a precision diamond-cut ribbed pattern for maximum brilliance. Hallmarked K.21, this set is a radiant expression of traditional South Asian jewelry heritage.",
    price: "$1,570",
    originalPrice: "$1,830",
    imageUrl: "/images/bangle4.jpg",
    categoryId: 5,
    categoryName: "Bracelet",
    isNewArrival: true,
    isTrending: false,
    badge: "New",
    weight: "15.47g",
  },
  {
    id: 10,
    name: "Set of 4 Twisted Pattern Gold Bangles",
    description: "A refined set of four 22K gold bangles with an elegant twisted design finish. Hallmarked K.21, these bangles make a perfect gift or bridal trousseau addition.",
    price: "$1,340",
    originalPrice: "$1,560",
    imageUrl: "/images/bangle5.jpg",
    categoryId: 5,
    categoryName: "Bracelet",
    isNewArrival: false,
    isTrending: true,
    badge: "Trending",
    weight: "12.41g",
  },
  {
    id: 11,
    name: "18K Gold Braided Diamond Cocktail Ring",
    description: "An extravagant 18K gold cocktail ring featuring intricately braided bands pavé-set with hundreds of brilliant diamonds. Hallmarked K.18, this statement ring is a masterwork of jewellery artistry.",
    price: "$1,260",
    originalPrice: "$1,480",
    imageUrl: "/images/ring6.jpg",
    categoryId: 1,
    categoryName: "Rings",
    isNewArrival: true,
    isTrending: true,
    badge: "New",
    weight: "14.77g",
  },
  {
    id: 12,
    name: "18K Gold Sculptural Wave Diamond Ring",
    description: "A bold sculptural ring in 18K gold, shaped into flowing waves and adorned with sparkling diamond accents. Hallmarked K.18, this avant-garde piece is wearable art at its finest.",
    price: "$800",
    originalPrice: "$940",
    imageUrl: "/images/ring7.jpg",
    categoryId: 1,
    categoryName: "Rings",
    isNewArrival: false,
    isTrending: true,
    badge: "Trending",
    weight: "9.40g",
  },
  {
    id: 13,
    name: "18K Gold Princess Silhouette Pendant Necklace",
    description: "A delicate 18K gold necklace featuring a circular pendant with an elegant female silhouette cutout. Hallmarked K.18, this refined piece is a poetic tribute to timeless femininity.",
    price: "$480",
    originalPrice: "$560",
    imageUrl: "/images/necklace1.jpg",
    categoryId: 4,
    categoryName: "Necklace",
    isNewArrival: true,
    isTrending: true,
    badge: "New",
    weight: null,
  },
  {
    id: 14,
    name: "18K Gold Four-Leaf Clover Station Necklace",
    description: "A luminous 18K gold necklace with five sparkling diamond-cut four-leaf clover pendants spaced elegantly along a fine chain. Hallmarked K.18, g.9.22.",
    price: "$790",
    originalPrice: "$920",
    imageUrl: "/images/necklace2.jpg",
    categoryId: 4,
    categoryName: "Necklace",
    isNewArrival: true,
    isTrending: false,
    badge: "New",
    weight: "9.22g",
  },
  {
    id: 15,
    name: "18K Gold Beaded Satellite Chain Necklace",
    description: "A minimalist 18K gold necklace featuring delicate gold and white gold beads evenly spaced along a fine cable chain. Hallmarked K.18, g.3.05. Perfect for everyday luxury.",
    price: "$260",
    originalPrice: "$310",
    imageUrl: "/images/necklace3.jpg",
    categoryId: 4,
    categoryName: "Necklace",
    isNewArrival: true,
    isTrending: false,
    badge: "New",
    weight: "3.05g",
  },
  {
    id: 16,
    name: "18K Gold Medusa Necklace, Bracelet & Ring Set",
    description: "A breathtaking 18K gold set featuring a large Medusa medallion on a paperclip chain necklace, a matching bracelet, and a coordinating ring. Hallmarked K.18. A collector's luxury set.",
    price: "$2,980",
    originalPrice: "$3,480",
    imageUrl: "/images/necklace4.jpg",
    categoryId: 4,
    categoryName: "Necklace",
    isNewArrival: false,
    isTrending: true,
    badge: "Trending",
    weight: null,
  },
  {
    id: 17,
    name: "18K Gold Medusa Cuban Link Set with Diamonds",
    description: "An opulent 18K gold set: a chunky Cuban link chain necklace with a diamond-encrusted Medusa medallion, plus a matching bracelet and earrings. Hallmarked K.18, g.66.28.",
    price: "$5,640",
    originalPrice: "$6,580",
    imageUrl: "/images/necklace5.jpg",
    categoryId: 4,
    categoryName: "Necklace",
    isNewArrival: false,
    isTrending: true,
    badge: "Trending",
    weight: "66.28g",
  },
  {
    id: 18,
    name: "18K Gold CD Logo Cuban Link Chain & Bracelet Set",
    description: "A designer-inspired 18K gold Cuban link chain necklace and matching bracelet, each centred with a diamond-set CD logo clasp. Hallmarked K.18. Bold, luxurious, and on-trend.",
    price: "$2,200",
    originalPrice: "$2,580",
    imageUrl: "/images/chain1.jpg",
    categoryId: 6,
    categoryName: "Chain",
    isNewArrival: true,
    isTrending: true,
    badge: "New",
    weight: null,
  },
  {
    id: 19,
    name: "18K Gold Heavy Cuban Link Chain & Bracelet Set",
    description: "A substantial, highly polished 18K gold Cuban link chain paired with a matching bracelet. Hallmarked K.18. A powerful everyday set that commands presence.",
    price: "$3,400",
    originalPrice: "$3,960",
    imageUrl: "/images/chain2.jpg",
    categoryId: 6,
    categoryName: "Chain",
    isNewArrival: false,
    isTrending: true,
    badge: "Trending",
    weight: null,
  },
  {
    id: 20,
    name: "18K Gold Double Cuban Link Chain & Bracelet Set",
    description: "Two rows of 18K gold Cuban links form this bold double-layer chain set, complete with a matching wide bracelet. Hallmarked K.18. A statement of unapologetic luxury.",
    price: "$3,100",
    originalPrice: "$3,620",
    imageUrl: "/images/chain3.jpg",
    categoryId: 6,
    categoryName: "Chain",
    isNewArrival: true,
    isTrending: false,
    badge: "New",
    weight: null,
  },
  {
    id: 21,
    name: "18K Gold Cuban Link Necklace & Bracelet Set",
    description: "A classic 18K gold Cuban link necklace and matching bracelet, both finished with a polished mirror shine. Hallmarked K.18. The cornerstone of any fine gold collection.",
    price: "$2,800",
    originalPrice: "$3,260",
    imageUrl: "/images/chain4.jpg",
    categoryId: 6,
    categoryName: "Chain",
    isNewArrival: false,
    isTrending: true,
    badge: "Trending",
    weight: null,
  },
  {
    id: 22,
    name: "18K Gold Rose Bloom Stud Earrings",
    description: "Enchanting 18K gold stud earrings crafted in the shape of a full-bloom rose. Hallmarked K.18, g.2.59. A romantic everyday essential.",
    price: "$220",
    originalPrice: "$260",
    imageUrl: "/images/earring1.jpg",
    categoryId: 2,
    categoryName: "Earrings",
    isNewArrival: true,
    isTrending: false,
    badge: "New",
    weight: "2.59g",
  },
  {
    id: 23,
    name: "18K Gold Diamond Flower Stud Earrings",
    description: "Petite 18K gold flower-shaped studs set with brilliant white diamonds in each petal. Hallmarked K.18, g.2.76. Timeless, delicate, and elegant.",
    price: "$236",
    originalPrice: "$276",
    imageUrl: "/images/earring2.jpg",
    categoryId: 2,
    categoryName: "Earrings",
    isNewArrival: true,
    isTrending: true,
    badge: "New",
    weight: "2.76g",
  },
  {
    id: 24,
    name: "18K Gold Diamond Bar Stud Earrings",
    description: "Sleek 18K gold bar studs encrusted with three rows of micro-pavé diamonds. Hallmarked K.18, g.2.68. A modern minimalist essential.",
    price: "$228",
    originalPrice: "$268",
    imageUrl: "/images/earring3.jpg",
    categoryId: 2,
    categoryName: "Earrings",
    isNewArrival: true,
    isTrending: false,
    badge: "New",
    weight: "2.68g",
  },
  {
    id: 25,
    name: "18K Gold Diamond Hoop Huggie Earrings",
    description: "Luxurious 18K gold huggie hoops encrusted with brilliant diamonds all around. Hallmarked K.18. Effortlessly versatile for day or evening wear.",
    price: "$380",
    originalPrice: "$440",
    imageUrl: "/images/earring4.jpg",
    categoryId: 2,
    categoryName: "Earrings",
    isNewArrival: false,
    isTrending: true,
    badge: "Trending",
    weight: null,
  },
  {
    id: 26,
    name: "18K Gold Dome Diamond Huggie Earrings",
    description: "Bold dome-shaped 18K gold huggie earrings pavé-set with row upon row of brilliant diamonds. Hallmarked K.18, g.3.85. A compact showpiece.",
    price: "$328",
    originalPrice: "$382",
    imageUrl: "/images/earring5.jpg",
    categoryId: 2,
    categoryName: "Earrings",
    isNewArrival: true,
    isTrending: true,
    badge: "New",
    weight: "3.85g",
  },
  {
    id: 27,
    name: "18K Gold Teardrop Diamond Drop Earrings",
    description: "Elegant 18K gold drop earrings featuring a tapered bar descending to a diamond-halo medallion. Hallmarked K.18, g.2.68. Perfect for evening glamour.",
    price: "$228",
    originalPrice: "$268",
    imageUrl: "/images/earring6.jpg",
    categoryId: 2,
    categoryName: "Earrings",
    isNewArrival: false,
    isTrending: true,
    badge: "Trending",
    weight: "2.68g",
  },
  {
    id: 28,
    name: "18K Gold Ruby & Emerald Charm Hoop Earrings",
    description: "Ornate 18K gold hoop earrings adorned with dangling ruby and emerald gemstone charms and golden leaf accents. Hallmarked K.18, g.4.73.",
    price: "$400",
    originalPrice: "$468",
    imageUrl: "/images/earring7.jpg",
    categoryId: 2,
    categoryName: "Earrings",
    isNewArrival: true,
    isTrending: false,
    badge: "New",
    weight: "4.73g",
  },
  {
    id: 29,
    name: "18K Gold Love Screw Bangle Bracelet",
    description: "An iconic 18K gold rigid bangle bracelet inspired by the love motif, featuring signature screw details around the entire circumference. Hallmarked K.18, g.28.77.",
    price: "$2,450",
    originalPrice: "$2,860",
    imageUrl: "/images/bracelet1.jpg",
    categoryId: 5,
    categoryName: "Bracelet",
    isNewArrival: true,
    isTrending: true,
    badge: "New",
    weight: "28.77g",
  },
];

export async function seedDatabase() {
  try {
    const existingCategories = await db.select().from(categoriesTable);
    if (existingCategories.length === 0) {
      logger.info("Seeding categories...");
      await db.execute(sql`ALTER SEQUENCE categories_id_seq RESTART WITH 1`);
      for (const cat of categories) {
        await db.insert(categoriesTable).values({
          name: cat.name,
          slug: cat.slug,
          imageUrl: cat.imageUrl,
        }).onConflictDoNothing();
      }
      logger.info(`Seeded ${categories.length} categories`);
    }

    const existingProducts = await db.select().from(productsTable);
    if (existingProducts.length === 0) {
      logger.info("Seeding products...");
      await db.execute(sql`ALTER SEQUENCE products_id_seq RESTART WITH 1`);
      for (const product of products) {
        await db.insert(productsTable).values({
          name: product.name,
          description: product.description,
          price: product.price,
          originalPrice: product.originalPrice,
          imageUrl: product.imageUrl,
          categoryId: product.categoryId,
          categoryName: product.categoryName,
          isNewArrival: product.isNewArrival,
          isTrending: product.isTrending,
          badge: product.badge,
          weight: product.weight,
        }).onConflictDoNothing();
      }
      logger.info(`Seeded ${products.length} products`);
    }
  } catch (err) {
    logger.error({ err }, "Error seeding database");
  }
}
