export interface CountryData {
  name: string;
  states: string[];
}

export const COUNTRIES: CountryData[] = [
  { name: "Afghanistan", states: ["Badakhshan","Badghis","Baghlan","Balkh","Bamiyan","Daikundi","Farah","Faryab","Ghazni","Ghor","Helmand","Herat","Jowzjan","Kabul","Kandahar","Kapisa","Khost","Kunar","Kunduz","Laghman","Logar","Nangarhar","Nimroz","Nuristan","Paktia","Paktika","Panjshir","Parwan","Samangan","Sar-e Pol","Takhar","Urozgan","Wardak","Zabul"] },
  { name: "Albania", states: ["Berat","Dibër","Durrës","Elbasan","Fier","Gjirokastër","Korçë","Kukës","Lezhë","Shkodër","Tirana","Vlorë"] },
  { name: "Algeria", states: ["Adrar","Aïn Defla","Aïn Témouchent","Algiers","Annaba","Batna","Béchar","Béjaïa","Biskra","Blida","Bordj Bou Arréridj","Bouira","Boumerdès","Chlef","Constantine","Djelfa","El Bayadh","El Oued","El Tarf","Ghardaïa","Guelma","Illizi","Jijel","Khenchela","Laghouat","M'Sila","Mascara","Médéa","Mila","Mostaganem","Naâma","Oran","Ouargla","Oum el Bouaghi","Relizane","Saïda","Sétif","Sidi Bel Abbès","Skikda","Souk Ahras","Tamanrasset","Tébessa","Tiaret","Tindouf","Tipaza","Tissemsilt","Tizi Ouzou","Tlemcen"] },
  { name: "Andorra", states: [] },
  { name: "Angola", states: ["Bengo","Benguela","Bié","Cabinda","Cuando Cubango","Cuanza Norte","Cuanza Sul","Cunene","Huambo","Huíla","Luanda","Lunda Norte","Lunda Sul","Malanje","Moxico","Namibe","Uíge","Zaire"] },
  { name: "Antigua and Barbuda", states: [] },
  { name: "Argentina", states: ["Buenos Aires","Catamarca","Chaco","Chubut","Córdoba","Corrientes","Entre Ríos","Formosa","Jujuy","La Pampa","La Rioja","Mendoza","Misiones","Neuquén","Río Negro","Salta","San Juan","San Luis","Santa Cruz","Santa Fe","Santiago del Estero","Tierra del Fuego","Tucumán"] },
  { name: "Armenia", states: ["Aragatsotn","Ararat","Armavir","Gegharkunik","Kotayk","Lori","Shirak","Syunik","Tavush","Vayots Dzor","Yerevan"] },
  { name: "Australia", states: ["Australian Capital Territory","New South Wales","Northern Territory","Queensland","South Australia","Tasmania","Victoria","Western Australia"] },
  { name: "Austria", states: ["Burgenland","Carinthia","Lower Austria","Salzburg","Styria","Tyrol","Upper Austria","Vienna","Vorarlberg"] },
  { name: "Azerbaijan", states: ["Absheron","Agdam","Agdash","Agstafa","Agsu","Astara","Baku","Balakan","Barda","Beylagan","Bilasuvar","Dashkasan","Fuzuli","Gadabay","Ganja","Goranboy","Goychay","Goygol","Hajigabul","Imishli","Ismailly","Jabrayil","Jalilabad","Khachmaz","Khankendi","Khizi","Khojaly","Khojawend","Kurdamir","Lachin","Lankaran","Lerik","Masally","Mingachevir","Nakhchivan","Neftchala","Oghuz","Qabala","Qakh","Qazakh","Quba","Qubadli","Qusar","Saatly","Sabirabad","Salyan","Shamakhi","Shamkir","Shirvan","Shaki","Shusha","Siyazan","Sumgayit","Tartar","Tovuz","Ujar","Yardymly","Yevlakh","Zangilan","Zaqatala","Zardab"] },
  { name: "Bahamas", states: [] },
  { name: "Bahrain", states: ["Capital","Central","Muharraq","Northern","Southern"] },
  { name: "Bangladesh", states: ["Barisal","Chittagong","Dhaka","Khulna","Mymensingh","Rajshahi","Rangpur","Sylhet"] },
  { name: "Barbados", states: [] },
  { name: "Belarus", states: ["Brest","Gomel","Grodno","Minsk","Mogilev","Vitebsk"] },
  { name: "Belgium", states: ["Brussels","Flanders","Wallonia"] },
  { name: "Belize", states: [] },
  { name: "Benin", states: ["Alibori","Atakora","Atlantique","Borgou","Collines","Donga","Kouffo","Littoral","Mono","Ouémé","Plateau","Zou"] },
  { name: "Bhutan", states: [] },
  { name: "Bolivia", states: ["Beni","Chuquisaca","Cochabamba","La Paz","Oruro","Pando","Potosí","Santa Cruz","Tarija"] },
  { name: "Bosnia and Herzegovina", states: ["Brčko District","Federation of Bosnia and Herzegovina","Republika Srpska"] },
  { name: "Botswana", states: [] },
  { name: "Brazil", states: ["Acre","Alagoas","Amapá","Amazonas","Bahia","Ceará","Distrito Federal","Espírito Santo","Goiás","Maranhão","Mato Grosso","Mato Grosso do Sul","Minas Gerais","Pará","Paraíba","Paraná","Pernambuco","Piauí","Rio de Janeiro","Rio Grande do Norte","Rio Grande do Sul","Rondônia","Roraima","Santa Catarina","São Paulo","Sergipe","Tocantins"] },
  { name: "Brunei", states: [] },
  { name: "Bulgaria", states: ["Blagoevgrad","Burgas","Dobrich","Gabrovo","Haskovo","Kardzhali","Kyustendil","Lovech","Montana","Pazardzhik","Pernik","Pleven","Plovdiv","Razgrad","Ruse","Shumen","Silistra","Sliven","Smolyan","Sofia","Sofia Province","Stara Zagora","Targovishte","Varna","Veliko Tarnovo","Vidin","Vratsa","Yambol"] },
  { name: "Burkina Faso", states: [] },
  { name: "Burundi", states: [] },
  { name: "Cambodia", states: [] },
  { name: "Cameroon", states: ["Adamawa","Centre","East","Far North","Littoral","North","Northwest","South","Southwest","West"] },
  { name: "Canada", states: ["Alberta","British Columbia","Manitoba","New Brunswick","Newfoundland and Labrador","Northwest Territories","Nova Scotia","Nunavut","Ontario","Prince Edward Island","Quebec","Saskatchewan","Yukon"] },
  { name: "Cape Verde", states: [] },
  { name: "Central African Republic", states: [] },
  { name: "Chad", states: [] },
  { name: "Chile", states: ["Antofagasta","Araucanía","Arica y Parinacota","Atacama","Aysén","Biobío","Coquimbo","Los Lagos","Los Ríos","Magallanes","Maule","Metropolitana","Ñuble","O'Higgins","Tarapacá","Valparaíso"] },
  { name: "China", states: ["Anhui","Beijing","Chongqing","Fujian","Gansu","Guangdong","Guangxi","Guizhou","Hainan","Hebei","Heilongjiang","Henan","Hong Kong","Hubei","Hunan","Inner Mongolia","Jiangsu","Jiangxi","Jilin","Liaoning","Macau","Ningxia","Qinghai","Shaanxi","Shandong","Shanghai","Shanxi","Sichuan","Tianjin","Tibet","Xinjiang","Yunnan","Zhejiang"] },
  { name: "Colombia", states: ["Amazonas","Antioquia","Arauca","Atlántico","Bogotá D.C.","Bolívar","Boyacá","Caldas","Caquetá","Casanare","Cauca","Cesar","Chocó","Córdoba","Cundinamarca","Guainía","Guaviare","Huila","La Guajira","Magdalena","Meta","Nariño","Norte de Santander","Putumayo","Quindío","Risaralda","San Andrés y Providencia","Santander","Sucre","Tolima","Valle del Cauca","Vaupés","Vichada"] },
  { name: "Comoros", states: [] },
  { name: "Congo", states: [] },
  { name: "Costa Rica", states: ["Alajuela","Cartago","Guanacaste","Heredia","Limón","Puntarenas","San José"] },
  { name: "Croatia", states: ["Bjelovar-Bilogora","Brod-Posavina","Dubrovnik-Neretva","Istria","Karlovac","Koprivnica-Križevci","Krapina-Zagorje","Lika-Senj","Medimurje","Osijek-Baranja","Požega-Slavonia","Primorje-Gorski Kotar","Šibenik-Knin","Sisak-Moslavina","Split-Dalmatia","Varaždin","Virovitica-Podravina","Vukovar-Srijem","Zadar","Zagreb","Zagreb County"] },
  { name: "Cuba", states: [] },
  { name: "Cyprus", states: [] },
  { name: "Czech Republic", states: ["Central Bohemian","Hradec Králové","Karlovy Vary","Liberec","Moravian-Silesian","Olomouc","Pardubice","Plzeň","Prague","South Bohemian","South Moravian","Ústí nad Labem","Vysočina","Zlín"] },
  { name: "Democratic Republic of the Congo", states: [] },
  { name: "Denmark", states: ["Capital Region","Central Denmark","North Denmark","Region Zealand","Southern Denmark"] },
  { name: "Djibouti", states: [] },
  { name: "Dominican Republic", states: ["Azua","Bahoruco","Barahona","Dajabón","Distrito Nacional","Duarte","El Seibo","Elías Piña","Espaillat","Hato Mayor","Hermanas Mirabal","Independencia","La Altagracia","La Romana","La Vega","María Trinidad Sánchez","Monseñor Nouel","Monte Cristi","Monte Plata","Pedernales","Peravia","Puerto Plata","Samaná","San Cristóbal","San José de Ocoa","San Juan","San Pedro de Macorís","Sánchez Ramírez","Santiago","Santiago Rodríguez","Santo Domingo","Valverde"] },
  { name: "Ecuador", states: ["Azuay","Bolívar","Cañar","Carchi","Chimborazo","Cotopaxi","El Oro","Esmeraldas","Galápagos","Guayas","Imbabura","Loja","Los Ríos","Manabí","Morona Santiago","Napo","Orellana","Pastaza","Pichincha","Santa Elena","Santo Domingo de los Tsáchilas","Sucumbíos","Tungurahua","Zamora Chinchipe"] },
  { name: "Egypt", states: ["Alexandria","Aswan","Asyut","Beheira","Beni Suef","Cairo","Dakahlia","Damietta","Faiyum","Gharbia","Giza","Ismailia","Kafr el-Sheikh","Luxor","Matruh","Minya","Monufia","New Valley","North Sinai","Port Said","Qalyubia","Qena","Red Sea","Sharqia","Sohag","South Sinai","Suez"] },
  { name: "El Salvador", states: [] },
  { name: "Equatorial Guinea", states: [] },
  { name: "Eritrea", states: [] },
  { name: "Estonia", states: [] },
  { name: "Eswatini", states: [] },
  { name: "Ethiopia", states: ["Addis Ababa","Afar","Amhara","Benishangul-Gumuz","Dire Dawa","Gambela","Harari","Oromia","Sidama","Somali","Southern Nations","Tigray"] },
  { name: "Fiji", states: [] },
  { name: "Finland", states: ["Central Finland","Central Ostrobothnia","Finland Proper","Kainuu","Kymenlaakso","Lapland","North Karelia","North Ostrobothnia","North Savo","Ostrobothnia","Päijät-Häme","Pirkanmaa","Satakunta","South Karelia","South Ostrobothnia","South Savo","Tavastia Proper","Uusimaa"] },
  { name: "France", states: ["Auvergne-Rhône-Alpes","Bourgogne-Franche-Comté","Bretagne","Centre-Val de Loire","Corse","Grand Est","Hauts-de-France","Île-de-France","Normandie","Nouvelle-Aquitaine","Occitanie","Pays de la Loire","Provence-Alpes-Côte d'Azur"] },
  { name: "Gabon", states: [] },
  { name: "Gambia", states: [] },
  { name: "Georgia", states: ["Adjara","Guria","Imereti","Kakheti","Kvemo Kartli","Mtskheta-Mtianeti","Racha-Lechkhumi","Samegrelo-Zemo Svaneti","Samtskhe-Javakheti","Shida Kartli","Tbilisi"] },
  { name: "Germany", states: ["Baden-Württemberg","Bavaria","Berlin","Brandenburg","Bremen","Hamburg","Hesse","Lower Saxony","Mecklenburg-Vorpommern","North Rhine-Westphalia","Rhineland-Palatinate","Saarland","Saxony","Saxony-Anhalt","Schleswig-Holstein","Thuringia"] },
  { name: "Ghana", states: ["Ahafo","Ashanti","Bono","Bono East","Central","Eastern","Greater Accra","North East","Northern","Oti","Savannah","Upper East","Upper West","Volta","Western","Western North"] },
  { name: "Greece", states: ["Attica","Central Greece","Central Macedonia","Crete","Eastern Macedonia","Epirus","Ionian Islands","North Aegean","Peloponnese","South Aegean","Thessaly","Western Greece","Western Macedonia"] },
  { name: "Grenada", states: [] },
  { name: "Guatemala", states: ["Alta Verapaz","Baja Verapaz","Chimaltenango","Chiquimula","El Progreso","Escuintla","Guatemala","Huehuetenango","Izabal","Jalapa","Jutiapa","Petén","Quetzaltenango","Quiché","Retalhuleu","Sacatepéquez","San Marcos","Santa Rosa","Sololá","Suchitepéquez","Totonicapán","Zacapa"] },
  { name: "Guinea", states: [] },
  { name: "Guinea-Bissau", states: [] },
  { name: "Guyana", states: [] },
  { name: "Haiti", states: [] },
  { name: "Honduras", states: ["Atlántida","Choluteca","Colón","Comayagua","Copán","Cortés","El Paraíso","Francisco Morazán","Gracias a Dios","Intibucá","Islas de la Bahía","La Paz","Lempira","Ocotepeque","Olancho","Santa Bárbara","Valle","Yoro"] },
  { name: "Hungary", states: ["Bács-Kiskun","Baranya","Békés","Borsod-Abaúj-Zemplén","Budapest","Csongrád-Csanád","Fejér","Győr-Moson-Sopron","Hajdú-Bihar","Heves","Jász-Nagykun-Szolnok","Komárom-Esztergom","Nógrád","Pest","Somogy","Szabolcs-Szatmár-Bereg","Tolna","Vas","Veszprém","Zala"] },
  { name: "Iceland", states: [] },
  { name: "India", states: ["Andaman and Nicobar Islands","Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chandigarh","Chhattisgarh","Dadra and Nagar Haveli and Daman and Diu","Delhi","Goa","Gujarat","Haryana","Himachal Pradesh","Jammu and Kashmir","Jharkhand","Karnataka","Kerala","Ladakh","Lakshadweep","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Puducherry","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal"] },
  { name: "Indonesia", states: ["Aceh","Bali","Bangka Belitung Islands","Banten","Bengkulu","Central Java","Central Kalimantan","Central Sulawesi","East Java","East Kalimantan","East Nusa Tenggara","Gorontalo","Jakarta","Jambi","Lampung","Maluku","North Kalimantan","North Maluku","North Sulawesi","North Sumatra","Papua","Riau","Riau Islands","South Kalimantan","South Sulawesi","South Sumatra","Southeast Sulawesi","Special Region of Yogyakarta","West Java","West Kalimantan","West Nusa Tenggara","West Papua","West Sulawesi","West Sumatra"] },
  { name: "Iran", states: ["Alborz","Ardabil","Bushehr","Chaharmahal and Bakhtiari","East Azerbaijan","Fars","Gilan","Golestan","Hamadan","Hormozgan","Ilam","Isfahan","Kerman","Kermanshah","Khuzestan","Kohgiluyeh and Boyer-Ahmad","Kurdistan","Lorestan","Markazi","Mazandaran","North Khorasan","Qazvin","Qom","Razavi Khorasan","Semnan","Sistan and Baluchestan","South Khorasan","Tehran","West Azerbaijan","Yazd","Zanjan"] },
  { name: "Iraq", states: ["Al Anbar","Al Muthanna","Al Qadisiyyah","Babylon","Baghdad","Basra","Dhi Qar","Diyala","Dohuk","Erbil","Karbala","Kirkuk","Maysan","Najaf","Nineveh","Saladin","Sulaymaniyah","Wasit"] },
  { name: "Ireland", states: ["Carlow","Cavan","Clare","Cork","Donegal","Dublin","Galway","Kerry","Kildare","Kilkenny","Laois","Leitrim","Limerick","Longford","Louth","Mayo","Meath","Monaghan","Offaly","Roscommon","Sligo","Tipperary","Waterford","Westmeath","Wexford","Wicklow"] },
  { name: "Israel", states: ["Central","Haifa","Jerusalem","Northern","Southern","Tel Aviv"] },
  { name: "Italy", states: ["Abruzzo","Aosta Valley","Apulia","Basilicata","Calabria","Campania","Emilia-Romagna","Friuli Venezia Giulia","Lazio","Liguria","Lombardy","Marche","Molise","Piedmont","Sardinia","Sicily","Trentino-South Tyrol","Tuscany","Umbria","Veneto"] },
  { name: "Jamaica", states: ["Clarendon","Hanover","Kingston","Manchester","Portland","Saint Andrew","Saint Ann","Saint Catherine","Saint Elizabeth","Saint James","Saint Mary","Saint Thomas","Trelawny","Westmoreland"] },
  { name: "Japan", states: ["Aichi","Akita","Aomori","Chiba","Ehime","Fukui","Fukuoka","Fukushima","Gifu","Gunma","Hiroshima","Hokkaido","Hyogo","Ibaraki","Ishikawa","Iwate","Kagawa","Kagoshima","Kanagawa","Kochi","Kumamoto","Kyoto","Mie","Miyagi","Miyazaki","Nagano","Nagasaki","Nara","Niigata","Oita","Okayama","Okinawa","Osaka","Saga","Saitama","Shiga","Shimane","Shizuoka","Tochigi","Tokushima","Tokyo","Tottori","Toyama","Wakayama","Yamagata","Yamaguchi","Yamanashi"] },
  { name: "Jordan", states: ["Ajloun","Amman","Aqaba","Balqa","Irbid","Jerash","Karak","Ma'an","Madaba","Mafraq","Tafilah","Zarqa"] },
  { name: "Kazakhstan", states: ["Akmola","Aktobe","Almaty","Almaty City","Atyrau","East Kazakhstan","Jambyl","Karaganda","Kostanay","Kyzylorda","Mangystau","North Kazakhstan","Nur-Sultan","Pavlodar","Shymkent","Turkestan","West Kazakhstan"] },
  { name: "Kenya", states: ["Baringo","Bomet","Bungoma","Busia","Elgeyo-Marakwet","Embu","Garissa","Homa Bay","Isiolo","Kajiado","Kakamega","Kericho","Kiambu","Kilifi","Kirinyaga","Kisii","Kisumu","Kitui","Kwale","Laikipia","Lamu","Machakos","Makueni","Mandera","Marsabit","Meru","Migori","Mombasa","Murang'a","Nairobi","Nakuru","Nandi","Narok","Nyamira","Nyandarua","Nyeri","Samburu","Siaya","Taita-Taveta","Tana River","Tharaka-Nithi","Trans-Nzoia","Turkana","Uasin Gishu","Vihiga","Wajir","West Pokot"] },
  { name: "Kuwait", states: ["Al Ahmadi","Al Asimah","Al Farwaniyah","Al Jahra","Hawalli","Mubarak Al-Kabeer"] },
  { name: "Kyrgyzstan", states: [] },
  { name: "Laos", states: [] },
  { name: "Latvia", states: [] },
  { name: "Lebanon", states: ["Akkar","Baalbek-Hermel","Beirut","Bekaa","Mount Lebanon","Nabatieh","North Lebanon","South Lebanon"] },
  { name: "Lesotho", states: [] },
  { name: "Liberia", states: [] },
  { name: "Libya", states: ["Benghazi","Derna","Fezzan","Ghat","Jabal al Akhdar","Jabal al Gharbi","Jafara","Jufra","Kufra","Marj","Misrata","Murzuq","Nalut","Nuqat al Khams","Sabha","Surt","Tripoli","Wadi al Hayaa","Wadi al Shatii","Zawiya"] },
  { name: "Liechtenstein", states: [] },
  { name: "Lithuania", states: [] },
  { name: "Luxembourg", states: [] },
  { name: "Madagascar", states: [] },
  { name: "Malawi", states: [] },
  { name: "Malaysia", states: ["Johor","Kedah","Kelantan","Kuala Lumpur","Labuan","Melaka","Negeri Sembilan","Pahang","Penang","Perak","Perlis","Putrajaya","Sabah","Sarawak","Selangor","Terengganu"] },
  { name: "Maldives", states: [] },
  { name: "Mali", states: [] },
  { name: "Malta", states: [] },
  { name: "Mauritania", states: [] },
  { name: "Mauritius", states: [] },
  { name: "Mexico", states: ["Aguascalientes","Baja California","Baja California Sur","Campeche","Chiapas","Chihuahua","Coahuila","Colima","Durango","Guanajuato","Guerrero","Hidalgo","Jalisco","Mexico City","Mexico State","Michoacán","Morelos","Nayarit","Nuevo León","Oaxaca","Puebla","Querétaro","Quintana Roo","San Luis Potosí","Sinaloa","Sonora","Tabasco","Tamaulipas","Tlaxcala","Veracruz","Yucatán","Zacatecas"] },
  { name: "Moldova", states: [] },
  { name: "Monaco", states: [] },
  { name: "Mongolia", states: [] },
  { name: "Montenegro", states: [] },
  { name: "Morocco", states: ["Beni Mellal-Khénifra","Casablanca-Settat","Drâa-Tafilalet","Fès-Meknès","Guelmim-Oued Noun","Laâyoune-Sakia El Hamra","Marrakech-Safi","Oriental","Rabat-Salé-Kénitra","Souss-Massa","Tanger-Tétouan-Al Hoceïma"] },
  { name: "Mozambique", states: [] },
  { name: "Myanmar", states: [] },
  { name: "Namibia", states: [] },
  { name: "Nepal", states: ["Bagmati","Gandaki","Karnali","Koshi","Lumbini","Madhesh","Sudurpashchim"] },
  { name: "Netherlands", states: ["Drenthe","Flevoland","Friesland","Gelderland","Groningen","Limburg","North Brabant","North Holland","Overijssel","South Holland","Utrecht","Zeeland"] },
  { name: "New Zealand", states: ["Auckland","Bay of Plenty","Canterbury","Gisborne","Hawke's Bay","Manawatū-Whanganui","Marlborough","Nelson","Northland","Otago","Southland","Taranaki","Tasman","Waikato","Wellington","West Coast"] },
  { name: "Nicaragua", states: [] },
  { name: "Niger", states: [] },
  { name: "Nigeria", states: ["Abia","Adamawa","Akwa Ibom","Anambra","Bauchi","Bayelsa","Benue","Borno","Cross River","Delta","Ebonyi","Edo","Ekiti","Enugu","FCT - Abuja","Gombe","Imo","Jigawa","Kaduna","Kano","Katsina","Kebbi","Kogi","Kwara","Lagos","Nasarawa","Niger","Ogun","Ondo","Osun","Oyo","Plateau","Rivers","Sokoto","Taraba","Yobe","Zamfara"] },
  { name: "North Korea", states: [] },
  { name: "North Macedonia", states: [] },
  { name: "Norway", states: ["Innlandet","Møre og Romsdal","Nordland","Oslo","Rogaland","Troms og Finnmark","Trøndelag","Vestfold og Telemark","Vestland","Viken"] },
  { name: "Oman", states: ["Ad Dakhiliyah","Al Batinah North","Al Batinah South","Al Buraymi","Al Wusta","Ash Sharqiyah North","Ash Sharqiyah South","Dhofar","Musandam","Muscat","Az Zahirah"] },
  { name: "Pakistan", states: ["Azad Kashmir","Balochistan","Gilgit-Baltistan","Islamabad Capital Territory","Khyber Pakhtunkhwa","Punjab","Sindh"] },
  { name: "Panama", states: [] },
  { name: "Papua New Guinea", states: [] },
  { name: "Paraguay", states: [] },
  { name: "Peru", states: ["Amazonas","Áncash","Apurímac","Arequipa","Ayacucho","Cajamarca","Callao","Cusco","Huancavelica","Huánuco","Ica","Junín","La Libertad","Lambayeque","Lima","Loreto","Madre de Dios","Moquegua","Pasco","Piura","Puno","San Martín","Tacna","Tumbes","Ucayali"] },
  { name: "Philippines", states: ["Abra","Agusan del Norte","Agusan del Sur","Aklan","Albay","Antique","Apayao","Aurora","Basilan","Bataan","Batanes","Batangas","Benguet","Biliran","Bohol","Bukidnon","Bulacan","Cagayan","Camarines Norte","Camarines Sur","Camiguin","Capiz","Catanduanes","Cavite","Cebu","Cotabato","Davao de Oro","Davao del Norte","Davao del Sur","Davao Occidental","Davao Oriental","Dinagat Islands","Eastern Samar","Guimaras","Ifugao","Ilocos Norte","Ilocos Sur","Iloilo","Isabela","Kalinga","La Union","Laguna","Lanao del Norte","Lanao del Sur","Leyte","Maguindanao","Marinduque","Masbate","Metro Manila","Misamis Occidental","Misamis Oriental","Mountain Province","Negros Occidental","Negros Oriental","Northern Samar","Nueva Ecija","Nueva Vizcaya","Occidental Mindoro","Oriental Mindoro","Palawan","Pampanga","Pangasinan","Quezon","Quirino","Rizal","Romblon","Samar","Sarangani","Siquijor","Sorsogon","South Cotabato","Southern Leyte","Sultan Kudarat","Sulu","Surigao del Norte","Surigao del Sur","Tarlac","Tawi-Tawi","Zambales","Zamboanga del Norte","Zamboanga del Sur","Zamboanga Sibugay"] },
  { name: "Poland", states: ["Greater Poland","Holy Cross","Kuyavian-Pomeranian","Lesser Poland","Lodz","Lower Silesian","Lublin","Lubusz","Masovian","Opole","Podlaskie","Pomeranian","Silesian","Subcarpathian","Warmian-Masurian","West Pomeranian"] },
  { name: "Portugal", states: ["Aveiro","Beja","Braga","Bragança","Castelo Branco","Coimbra","Évora","Faro","Guarda","Leiria","Lisbon","Portalegre","Porto","Santarém","Setúbal","Viana do Castelo","Vila Real","Viseu"] },
  { name: "Qatar", states: ["Ad Dawhah","Al Khor","Al Rayyan","Al Shamal","Al Wakrah","Ash Shahaniyah","Az Za'ayin","Umm Salal"] },
  { name: "Romania", states: ["Alba","Arad","Argeș","Bacău","Bihor","Bistrița-Năsăud","Botoșani","Brăila","Brașov","Bucharest","Buzău","Călărași","Cluj","Constanța","Covasna","Dâmbovița","Dolj","Galați","Giurgiu","Gorj","Harghita","Hunedoara","Ialomița","Iași","Ilfov","Maramureș","Mehedinți","Mureș","Neamț","Olt","Prahova","Sălaj","Satu Mare","Sibiu","Suceava","Teleorman","Timișoara","Tulcea","Vâlcea","Vaslui","Vrancea"] },
  { name: "Russia", states: ["Adygea","Altai Krai","Altai Republic","Amur Oblast","Arkhangelsk Oblast","Astrakhan Oblast","Bashkortostan","Belgorod Oblast","Bryansk Oblast","Buryatia","Chechnya","Chelyabinsk Oblast","Chukotka Autonomous Okrug","Chuvashia","Dagestan","Ingushetia","Irkutsk Oblast","Ivanovo Oblast","Jewish Autonomous Oblast","Kabardino-Balkaria","Kaliningrad Oblast","Kalmykia","Kamchatka Krai","Karachay-Cherkessia","Karelia","Kemerovo Oblast","Khabarovsk Krai","Khanty-Mansi Autonomous Okrug","Kirov Oblast","Komi","Kostroma Oblast","Krasnodar Krai","Krasnoyarsk Krai","Kurgan Oblast","Kursk Oblast","Leningrad Oblast","Lipetsk Oblast","Magadan Oblast","Mari El","Mordovia","Moscow","Moscow Oblast","Murmansk Oblast","Nenets Autonomous Okrug","Nizhny Novgorod Oblast","North Ossetia–Alania","Novgorod Oblast","Novosibirsk Oblast","Omsk Oblast","Orenburg Oblast","Orel Oblast","Penza Oblast","Perm Krai","Primorsky Krai","Pskov Oblast","Rostov Oblast","Ryazan Oblast","Sakha","Sakhalin Oblast","Samara Oblast","Saint Petersburg","Saratov Oblast","Smolensk Oblast","Stavropol Krai","Sverdlovsk Oblast","Tambov Oblast","Tatarstan","Tomsk Oblast","Tula Oblast","Tuva","Tver Oblast","Tyumen Oblast","Udmurtia","Ulyanovsk Oblast","Vladimir Oblast","Volgograd Oblast","Vologda Oblast","Voronezh Oblast","Yamalo-Nenets Autonomous Okrug","Yaroslavl Oblast","Zabaykalsky Krai"] },
  { name: "Rwanda", states: [] },
  { name: "Saint Kitts and Nevis", states: [] },
  { name: "Saint Lucia", states: [] },
  { name: "Saint Vincent and the Grenadines", states: [] },
  { name: "Samoa", states: [] },
  { name: "San Marino", states: [] },
  { name: "Saudi Arabia", states: ["Asir","Al Bahah","Al Jawf","Al Madinah","Al Qassim","Eastern Province","Ha'il","Jazan","Mecca","Najran","Northern Borders","Riyadh","Tabuk"] },
  { name: "Senegal", states: [] },
  { name: "Serbia", states: ["Belgrade","Bor","Braničevo","Central Banat","Jablanica","Kolubara","Mačva","Moravica","Nišava","North Bačka","North Banat","Pčinja","Pirot","Podunavlje","Pomoravlje","Rasina","Raška","South Bačka","South Banat","Srem","Šumadija","Toplica","Vojvodina","Zaječar","Zlatibor"] },
  { name: "Seychelles", states: [] },
  { name: "Sierra Leone", states: [] },
  { name: "Singapore", states: [] },
  { name: "Slovakia", states: ["Banská Bystrica","Bratislava","Košice","Nitra","Prešov","Trenčín","Trnava","Žilina"] },
  { name: "Slovenia", states: [] },
  { name: "Solomon Islands", states: [] },
  { name: "Somalia", states: [] },
  { name: "South Africa", states: ["Eastern Cape","Free State","Gauteng","KwaZulu-Natal","Limpopo","Mpumalanga","North West","Northern Cape","Western Cape"] },
  { name: "South Korea", states: ["Busan","Chungcheongbuk-do","Chungcheongnam-do","Daegu","Daejeon","Gangwon-do","Gwangju","Gyeonggi-do","Gyeongsangbuk-do","Gyeongsangnam-do","Incheon","Jeju","Jeollabuk-do","Jeollanam-do","Sejong","Seoul","Ulsan"] },
  { name: "South Sudan", states: [] },
  { name: "Spain", states: ["Andalusia","Aragon","Asturias","Balearic Islands","Basque Country","Canary Islands","Cantabria","Castilla-La Mancha","Castile and León","Catalonia","Ceuta","Community of Madrid","Extremadura","Galicia","La Rioja","Melilla","Murcia","Navarre","Valencia"] },
  { name: "Sri Lanka", states: ["Central","Eastern","North Central","North Western","Northern","Sabaragamuwa","Southern","Uva","Western"] },
  { name: "Sudan", states: [] },
  { name: "Suriname", states: [] },
  { name: "Sweden", states: ["Blekinge","Dalarna","Gävleborg","Gotland","Halland","Jämtland","Jönköping","Kalmar","Kronoberg","Norrbotten","Örebro","Östergötland","Skåne","Södermanland","Stockholm","Uppsala","Värmland","Västerbotten","Västernorrland","Västmanland","Västra Götaland"] },
  { name: "Switzerland", states: ["Aargau","Appenzell Ausserrhoden","Appenzell Innerrhoden","Basel-Landschaft","Basel-Stadt","Bern","Fribourg","Geneva","Glarus","Graubünden","Jura","Lucerne","Neuchâtel","Nidwalden","Obwalden","Schaffhausen","Schwyz","Solothurn","St. Gallen","Thurgau","Ticino","Uri","Valais","Vaud","Zug","Zurich"] },
  { name: "Syria", states: [] },
  { name: "Taiwan", states: ["Changhua","Chiayi City","Chiayi County","Hsinchu City","Hsinchu County","Hualien","Kaohsiung","Keelung","Kinmen","Lienchiang","Miaoli","Nantou","New Taipei","Penghu","Pingtung","Taichung","Tainan","Taipei","Taitung","Taoyuan","Yilan","Yunlin"] },
  { name: "Tajikistan", states: [] },
  { name: "Tanzania", states: ["Arusha","Dar es Salaam","Dodoma","Geita","Iringa","Kagera","Katavi","Kigoma","Kilimanjaro","Lindi","Manyara","Mara","Mbeya","Morogoro","Mtwara","Mwanza","Njombe","Pemba North","Pemba South","Pwani","Rukwa","Ruvuma","Shinyanga","Simiyu","Singida","Songwe","Tabora","Tanga","Zanzibar North","Zanzibar South","Zanzibar West"] },
  { name: "Thailand", states: ["Amnat Charoen","Ang Thong","Bangkok","Bueng Kan","Buriram","Chachoengsao","Chai Nat","Chaiyaphum","Chanthaburi","Chiang Mai","Chiang Rai","Chon Buri","Chumphon","Kalasin","Kamphaeng Phet","Kanchanaburi","Khon Kaen","Krabi","Lampang","Lamphun","Loei","Lop Buri","Mae Hong Son","Maha Sarakham","Mukdahan","Nakhon Nayok","Nakhon Pathom","Nakhon Phanom","Nakhon Ratchasima","Nakhon Sawan","Nakhon Si Thammarat","Nan","Narathiwat","Nong Bua Lam Phu","Nong Khai","Nonthaburi","Pathum Thani","Pattani","Phang Nga","Phatthalung","Phayao","Phetchabun","Phetchaburi","Phichit","Phitsanulok","Phra Nakhon Si Ayutthaya","Phrae","Phuket","Prachin Buri","Prachuap Khiri Khan","Ranong","Ratchaburi","Rayong","Roi Et","Sa Kaeo","Sakon Nakhon","Samut Prakan","Samut Sakhon","Samut Songkhram","Sara Buri","Satun","Sing Buri","Sisaket","Songkhla","Sukhothai","Suphan Buri","Surat Thani","Surin","Tak","Trang","Trat","Ubon Ratchathani","Udon Thani","Uthai Thani","Uttaradit","Yala","Yasothon"] },
  { name: "Timor-Leste", states: [] },
  { name: "Togo", states: [] },
  { name: "Tonga", states: [] },
  { name: "Trinidad and Tobago", states: [] },
  { name: "Tunisia", states: ["Ariana","Béja","Ben Arous","Bizerte","Gabès","Gafsa","Jendouba","Kairouan","Kasserine","Kebili","Kef","Mahdia","Manouba","Medenine","Monastir","Nabeul","Sfax","Sidi Bouzid","Siliana","Sousse","Tataouine","Tozeur","Tunis","Zaghouan"] },
  { name: "Turkey", states: ["Adana","Adıyaman","Afyonkarahisar","Ağrı","Aksaray","Amasya","Ankara","Antalya","Ardahan","Artvin","Aydın","Balıkesir","Bartın","Batman","Bayburt","Bilecik","Bingöl","Bitlis","Bolu","Burdur","Bursa","Çanakkale","Çankırı","Çorum","Denizli","Diyarbakır","Düzce","Edirne","Elazığ","Erzincan","Erzurum","Eskişehir","Gaziantep","Giresun","Gümüşhane","Hakkari","Hatay","Iğdır","Isparta","İstanbul","İzmir","Kahramanmaraş","Karabük","Karaman","Kars","Kastamonu","Kayseri","Kilis","Kırıkkale","Kırklareli","Kırşehir","Kocaeli","Konya","Kütahya","Malatya","Manisa","Mardin","Mersin","Muğla","Muş","Nevşehir","Niğde","Ordu","Osmaniye","Rize","Sakarya","Samsun","Şanlıurfa","Siirt","Sinop","Şırnak","Sivas","Tekirdağ","Tokat","Trabzon","Tunceli","Uşak","Van","Yalova","Yozgat","Zonguldak"] },
  { name: "Turkmenistan", states: [] },
  { name: "Uganda", states: [] },
  { name: "Ukraine", states: ["Cherkasy","Chernihiv","Chernivtsi","Dnipropetrovsk","Donetsk","Ivano-Frankivsk","Kharkiv","Kherson","Khmelnytskyi","Kyiv","Kirovohrad","Luhansk","Lviv","Mykolaiv","Odessa","Poltava","Rivne","Sumy","Ternopil","Vinnytsia","Volyn","Zakarpattia","Zaporizhzhia","Zhytomyr"] },
  { name: "United Arab Emirates", states: ["Abu Dhabi","Ajman","Dubai","Fujairah","Ras Al Khaimah","Sharjah","Umm Al Quwain"] },
  { name: "United Kingdom", states: ["England - East Midlands","England - East of England","England - London","England - North East","England - North West","England - South East","England - South West","England - West Midlands","England - Yorkshire and the Humber","Northern Ireland","Scotland","Wales"] },
  { name: "United States", states: ["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","Washington D.C.","West Virginia","Wisconsin","Wyoming"] },
  { name: "Uruguay", states: [] },
  { name: "Uzbekistan", states: [] },
  { name: "Vanuatu", states: [] },
  { name: "Venezuela", states: [] },
  { name: "Vietnam", states: ["An Giang","Bà Rịa-Vũng Tàu","Bắc Giang","Bắc Kạn","Bạc Liêu","Bắc Ninh","Bến Tre","Bình Định","Bình Dương","Bình Phước","Bình Thuận","Cà Mau","Cần Thơ","Cao Bằng","Đà Nẵng","Đắk Lắk","Đắk Nông","Điện Biên","Đồng Nai","Đồng Tháp","Gia Lai","Hà Giang","Hà Nam","Hà Nội","Hà Tĩnh","Hải Dương","Hải Phòng","Hậu Giang","Hòa Bình","Hưng Yên","Khánh Hòa","Kiên Giang","Kon Tum","Lai Châu","Lâm Đồng","Lạng Sơn","Lào Cai","Long An","Nam Định","Nghệ An","Ninh Bình","Ninh Thuận","Phú Thọ","Phú Yên","Quảng Bình","Quảng Nam","Quảng Ngãi","Quảng Ninh","Quảng Trị","Sóc Trăng","Sơn La","Tây Ninh","Thái Bình","Thái Nguyên","Thanh Hóa","Thừa Thiên Huế","Tiền Giang","TP. Hồ Chí Minh","Trà Vinh","Tuyên Quang","Vĩnh Long","Vĩnh Phúc","Yên Bái"] },
  { name: "Yemen", states: [] },
  { name: "Zambia", states: ["Central","Copperbelt","Eastern","Luapula","Lusaka","Muchinga","North-Western","Northern","Southern","Western"] },
  { name: "Zimbabwe", states: ["Bulawayo","Harare","Manicaland","Mashonaland Central","Mashonaland East","Mashonaland West","Masvingo","Matabeleland North","Matabeleland South","Midlands"] },
];
